### PR TITLE
failing test for space preservation

### PR DESCRIPTION
**Pull request by retorquere**

### CODE REVIEW

**Comment by retorquere** [comment]
Codacy and your linter disagree. The one wants single qoutes, the other double qoutes.

**Comment by bdougherty** [comment]
Thanks for taking a crack at the implementation. After thinking about it, I'd prefer that it be added as an option that's off by default. Would you mind updating it to be an option? If not, I will try to get to it soon.

I removed Codacy, so it shouldn't be an issue going forward.

**Comment by retorquere** [comment]
Added an option, off by default.

**Comment by Christilut** [comment]
Just ran into this too, any chance this can get merged? I know it's almost 2 years later :D

**Comment by bdougherty** [comment]
Added in f07191fa493301c4a589830076c4d8794aaee754.

**Pull request closed without merging**
